build:
  system_packages:
    - "wget"
    - "ffmpeg"
    - "libgl1-mesa-glx"
  python_packages:
    - "websocket-client==1.6.4"
    - "accelerate==0.23.0"
    - "opencv-python==4.10.0.84"
    - "boto3==1.35.9"
    - "pillow==10.4.0"
    - "torchvision==0.19.0"
    - "einops==0.8.0"
    - "transformers==4.44.2"
    - "scipy==1.14.1"
    - "torchsde==0.2.6"
    - "aiohttp==3.10.5"
    - "safetensors==0.4.4"
    
